Repository whyphi/zap, pull requests merged in 2024-08, with the labels that each got.

#98 Feat/get rush analytics
  chalicelib/api/events_rush.py
  chalicelib/services/EventsRushService.py
Labels: feature

#97 lint: fix lint warnings
  chalicelib/api/applicants.py
  chalicelib/api/insights.py
  chalicelib/api/listings.py
  chalicelib/s3.py
  chalicelib/services/AccountabilityService.py
  chalicelib/services/EventsMemberService.py
  chalicelib/services/InsightsService.py
  chalicelib/services/ListingService.py
  chalicelib/utils.py
  tests/api/test_applicants.py
  tests/api/test_events_members.py
  tests/api/test_events_rush.py
  tests/api/test_insights.py
  tests/api/test_listings.py
  tests/services/test_applicant_service.py
  tests/services/test_events_member_service.py
  tests/services/test_insights_service.py
  tests/services/test_listing_service.py
  tests/test_decorators.py
  tests/test_dynamodb.py
Labels: improvement

#99 feat: implement family tree get filter api
  chalicelib/api/members.py
  chalicelib/services/MemberService.py
Labels: feature

#101 Feat/analytics detail view zap
  chalicelib/api/events_rush.py
  chalicelib/services/EventsRushService.py
  tests/api/test_events_rush.py
Labels: refactor

#89 merge: `v2.0`
  app.py
  chalicelib/api/accountability.py
  chalicelib/api/applicants.py
  chalicelib/api/events.py
  chalicelib/api/events_member.py
  chalicelib/api/events_rush.py
  chalicelib/api/insights.py
  chalicelib/api/listings.py
  chalicelib/api/members.py
  chalicelib/modules/mongo.py
  chalicelib/s3.py
  chalicelib/services/AccountabilityService.py
  chalicelib/services/EventService.py
  chalicelib/services/EventsMemberService.py
  chalicelib/services/EventsRushService.py
  chalicelib/services/InsightsService.py
  chalicelib/services/ListingService.py
  chalicelib/services/MemberService.py
  chalicelib/utils.py
  tests/api/test_applicants.py
  tests/api/test_events.py
  tests/api/test_events_members.py
  tests/api/test_events_rush.py
  tests/api/test_insights.py
  tests/api/test_listings.py
  tests/api/test_members.py
  tests/services/test_applicant_service.py
  tests/services/test_events_member_service.py
  tests/services/test_insights_service.py
  tests/services/test_listing_service.py
  tests/test_decorators.py
  tests/test_dynamodb.py
Labels: breaking change

#102 fixed analytics endpoint
  chalicelib/api/events_rush.py
Labels: bug

#103 fixed polciy to allow delete s3 objects
  .chalice/policy-dev.json
  .chalice/policy-prod.json
Labels: bug

#104 Release: `v/2.0.0`
  .chalice/policy-dev.json
  .chalice/policy-prod.json
  app.py
  chalicelib/api/accountability.py
  chalicelib/api/applicants.py
  chalicelib/api/events.py
  chalicelib/api/events_member.py
  chalicelib/api/events_rush.py
  chalicelib/api/insights.py
  chalicelib/api/listings.py
  chalicelib/api/members.py
  chalicelib/modules/mongo.py
  chalicelib/s3.py
  chalicelib/services/AccountabilityService.py
  chalicelib/services/EventService.py
  chalicelib/services/EventsMemberService.py
  chalicelib/services/EventsRushService.py
  chalicelib/services/InsightsService.py
  chalicelib/services/ListingService.py
  chalicelib/services/MemberService.py
  chalicelib/utils.py
  tests/api/test_applicants.py
  tests/api/test_events.py
  tests/api/test_events_members.py
  tests/api/test_events_rush.py
  tests/api/test_insights.py
  tests/api/test_listings.py
  tests/api/test_members.py
  tests/services/test_applicant_service.py
  tests/services/test_events_member_service.py
  tests/services/test_insights_service.py
  tests/services/test_listing_service.py
  tests/test_decorators.py
  tests/test_dynamodb.py
Labels: release

#106 Merge: `2.0.1`
  chalicelib/services/EventsRushService.py
  chalicelib/utils.py
Labels: fix, refactor

#107 Release: `2.0.1`
  chalicelib/services/EventsRushService.py
  chalicelib/utils.py
Labels: release
