Repository whyphi/zap, pull requests merged in 2024-07, with the labels that each got.

#80 feat: Implement Ruff Pre Commit Hook
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  app.py
Labels: feature

#86 Fix/add mongomock unittests
  chalicelib/modules/mongo.py
  chalicelib/services/EventService.py
  tests/services/test_event_service.py
Labels: fix, improvement

#88 Fix/add mongomock unittests
  chalicelib/modules/mongo.py
  chalicelib/services/EventService.py
  tests/services/test_event_service.py
Labels: fix

#90 Feat/enable rush event cover image zap
  chalicelib/s3.py
  chalicelib/services/EventService.py
Labels: feature, improvement

#91 patched bug not being able to update event
  chalicelib/services/EventService.py
Labels: fix

#92 fixed deleting rush event
  chalicelib/services/EventService.py
Labels: fix

#93 Refactor/split event service and split attendees into separate collection
  app.py
  chalicelib/api/events.py
  chalicelib/api/events_member.py
  chalicelib/api/events_rush.py
  chalicelib/services/EventService.py
  chalicelib/services/EventsMemberService.py
  chalicelib/services/EventsRushService.py
  tests/api/test_events.py
  tests/api/test_events_members.py
  tests/api/test_events_rush.py
  tests/services/test_events_member_service.py
Labels: refactor
