Repository whyphi/zap, pull requests merged in 2025-06, with the labels that each got.

#145 feat: Implement PR Label Check Workflow
  .github/workflows/pr-label-check.yml
Labels: improvement

#149 Fix/will/migration/remove job listings
  .github/workflows/coverage.yml
  Pipfile
  Pipfile.lock
  app.py
  chalicelib/api/broadcast.py
  chalicelib/services/BroadcastService.py
  chalicelib/services/JobPostingService.py
  tests/services/test_job_posting_service.py
Labels: fix

#150 dev/v3.1 release (supabase migration)
  .chalice/config.json
  .chalice/policy-dev.json
  .chalice/policy-prod.json
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/supabase/ci.yml
  .github/workflows/supabase/production.yml
  .github/workflows/supabase/staging.yml
  .gitignore
  Pipfile
  Pipfile.lock
  app.py
  chalicelib/api/applicants.py
  chalicelib/api/broadcast.py
  chalicelib/api/listings.py
  chalicelib/handlers/error_handler.py
  chalicelib/models/application.py
  chalicelib/modules/supabase_client.py
  chalicelib/repositories/base_repository.py
  chalicelib/repositories/repository_factory.py
  chalicelib/services/ApplicantService.py
  chalicelib/services/BroadcastService.py
  chalicelib/services/JobPostingService.py
  chalicelib/services/ListingService.py
  chalicelib/utils.py
  supabase/.gitignore
  supabase/config.toml
  supabase/migrations/20250508021135_init_dynamo.sql
  supabase/seed.sql
  tests/repositories/__init__.py
  tests/repositories/test_supabase_repositories.py
  tests/services/test_applicant_service.py
  tests/services/test_job_posting_service.py
  tests/services/test_listing_service.py
  tests/test_decorators.py
Labels: refactor

#152 Fixed nested workflows
  .github/workflows/supabase-ci.yml
  .github/workflows/supabase-production.yml
  .github/workflows/supabase-staging.yml
Labels: fix

#146 v3.1 Release
  .chalice/config.json
  .chalice/policy-dev.json
  .chalice/policy-prod.json
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/supabase-ci.yml
  .github/workflows/supabase-production.yml
  .github/workflows/supabase-staging.yml
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  app.py
  chalicelib/api/accountability.py
  chalicelib/api/announcements.py
  chalicelib/api/applicants.py
  chalicelib/api/events_member.py
  chalicelib/api/events_rush.py
  chalicelib/api/insights.py
  chalicelib/api/listings.py
  chalicelib/api/members.py
  chalicelib/api/monitoring.py
  chalicelib/decorators.py
  chalicelib/events/__init__.py
  chalicelib/events/test.py
  chalicelib/handlers/error_handler.py
  chalicelib/models/application.py
  chalicelib/modules/google_sheets.py
  chalicelib/modules/supabase_client.py
  chalicelib/repositories/base_repository.py
  chalicelib/repositories/repository_factory.py
  chalicelib/services/AccountabilityService.py
  chalicelib/services/ApplicantService.py
  chalicelib/services/EventsMemberService.py
  chalicelib/services/EventsRushService.py
  chalicelib/services/ListingService.py
  chalicelib/services/MemberService.py
  chalicelib/utils.py
  supabase/.gitignore
  supabase/config.toml
  supabase/migrations/20250508021135_init_dynamo.sql
  supabase/seed.sql
  tests/api/test_applicants.py
  tests/api/test_events_members.py
  tests/api/test_events_rush.py
  tests/api/test_insights.py
  tests/api/test_listings.py
  tests/api/test_members.py
  tests/events/__init__.py
  tests/events/test_test.py
  tests/repositories/__init__.py
  tests/repositories/test_supabase_repositories.py
  tests/services/test_applicant_service.py
  tests/services/test_listing_service.py
  tests/test_decorators.py
  tools/README.md
  tools/generate_jwt_token.py
Labels: release

#153 Supabase declarative schemas
  supabase/config.toml
  supabase/migrations/20250508021135_init_dynamo.sql
  supabase/migrations/20250608190336_baseline_schemas.sql
  supabase/schemas/applications.sql
  supabase/schemas/listings.sql
Labels: refactor
